### ISSUE TITLE
CentOS: Unhandled Exception

### ISSUE THREAD

**Issue by AlexChien** [AntShares/AntShares#6]
Trying to launch a miner node in CentOS 7.2 following wiki guid, but failed with exception:

````
-> dotnet ./Miner.dll /rpc

Unhandled Exception: AntShares.Implementations.Blockchains.LevelDB.LevelDBException: Corruption: corrupted compressed block contents
   at AntShares.Implementations.Blockchains.LevelDB.NativeHelper.CheckError(IntPtr error)
   at AntShares.Implementations.Blockchains.LevelDB.Iterator.CheckError()
   at AntShares.Implementations.Blockchains.LevelDB.Iterator.Key()
   at AntShares.Implementations.Blockchains.LevelDB.Helper.<Find>d__0`1.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__3.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__157`2.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at AntShares.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at AntShares.Shell.MainService.OnStart(String[] args)
   at AntShares.Services.ConsoleServiceBase.Run(String[] args)
   at AntShares.Program.Main(String[] args)
Aborted
````

Seems LevelDB related, please advise how to proceed.

**Comment by AlexChien** [comment]
It seems the Chain data directory is corrupted.  After `rm -r Chain` and restart the node, it's working fine now.
